version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # app:
  #   build: .
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_DATABASE: myapp
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   volumes:
  #     - .:/app
  #   command: npm start

volumes:
  mysql_data:
  redis_data:
